import { Metadata } from 'next';

export const seoConfig = {
  baseUrl: 'https://docsauraflow.com',
  siteName: 'DocsAuraFlow',
  description: 'Free online document and image processing tools. Convert PDF to Word, enhance images with AI upscaler, remove backgrounds, create professional resumes, and more.',
  keywords: [
    'DocsAuraFlow',
    'docsauraflow',
    'PDF to Word converter',
    'Word to PDF converter',
    'document converter',
    'image converter',
    'AI image upscaler',
    'background remover',
    'resume builder',
    'PDF form filler',
    'free online tools',
    'document processing',
    'image enhancement',
    'file conversion',
    'professional tools',
    'no registration',
    'online PDF tools',
    'image editing tools',
    'AI tools',
    'document suite',
    'PDF converter',
    'image upscaler',
    'background removal',
    'resume generator',
    'form filler',
    'free tools',
    'web tools',
    'document editing',
    'image processing',
    'file converter',
    'online converter',
    'PDF editor',
    'image editor',
    'AI enhancement',
    'document tools',
    'image tools',
    'conversion tools',
    'professional resume',
    'PDF forms',
    'online editor',
    'free converter',
    'document processing tools',
    'image processing tools',
    'AI-powered tools',
    'online utilities',
    'web applications',
    'document management',
    'image management',
    'file processing',
    'online services',
    'free services',
    'document conversion',
    'image conversion',
    'PDF processing',
    'image optimization',
    'document optimization',
    'online productivity tools',
    'business tools',
    'office tools',
    'document workflow',
    'image workflow',
    'file management',
    'online workspace',
    'digital tools',
    'productivity suite',
    'document suite',
    'image suite',
    'conversion suite',
    'online toolkit',
    'web toolkit',
    'document toolkit',
    'image toolkit',
    'free toolkit',
    'conversion toolkit',
    'processing toolkit',
    'editing toolkit',
    'enhancement toolkit',
    'optimization toolkit',
    'management toolkit',
    'workflow toolkit',
    'productivity toolkit',
    'business toolkit',
    'office toolkit',
    'digital toolkit'
  ],
};

export const toolPages = {
  'pdf-to-word': {
    title: 'PDF to Word Converter - Free Online Tool | DocsAuraFlow',
    description: 'Convert PDF to Word documents online for free. Transform your PDF files into editable Word documents with preserved formatting. Fast, secure, and no registration required.',
    keywords: [
      'PDF to Word converter',
      'PDF to Word online',
      'convert PDF to Word',
      'PDF to Word free',
      'PDF to Word document',
      'PDF to Word tool',
      'PDF to Word conversion',
      'PDF to Word software',
      'PDF to Word app',
      'PDF to Word service',
      'PDF to Word website',
      'PDF to Word utility',
      'PDF to Word processor',
      'PDF to Word editor',
      'PDF to Word transformer',
      'PDF to Word extractor',
      'PDF to Word parser',
      'PDF to Word reader',
      'PDF to Word writer',
      'PDF to Word generator',
      'PDF to Word creator',
      'PDF to Word maker',
      'PDF to Word builder',
      'PDF to Word formatter',
      'PDF to Word optimizer',
      'PDF to Word enhancer',
      'PDF to Word improver',
      'PDF to Word modifier',
      'PDF to Word changer',
      'PDF to Word translator',
      'PDF to Word converter online',
      'PDF to Word converter free',
      'PDF to Word converter tool',
      'PDF to Word converter software',
      'PDF to Word converter app',
      'PDF to Word converter service',
      'PDF to Word converter website',
      'PDF to Word converter utility',
      'PDF to Word converter processor',
      'PDF to Word converter editor',
      'PDF to Word converter transformer',
      'PDF to Word converter extractor',
      'PDF to Word converter parser',
      'PDF to Word converter reader',
      'PDF to Word converter writer',
      'PDF to Word converter generator',
      'PDF to Word converter creator',
      'PDF to Word converter maker',
      'PDF to Word converter builder',
      'PDF to Word converter formatter',
      'PDF to Word converter optimizer',
      'PDF to Word converter enhancer',
      'PDF to Word converter improver',
      'PDF to Word converter modifier',
      'PDF to Word converter changer',
      'PDF to Word converter translator'
    ],
  },
  'word-to-pdf': {
    title: 'Word to PDF Converter - Free Online Tool | DocsAuraFlow',
    description: 'Convert Word documents to PDF format online for free. Transform your Word files into professional PDF documents with preserved formatting. Fast, secure, and no registration required.',
    keywords: [
      'Word to PDF converter',
      'Word to PDF online',
      'convert Word to PDF',
      'Word to PDF free',
      'Word to PDF document',
      'Word to PDF tool',
      'Word to PDF conversion',
      'Word to PDF software',
      'Word to PDF app',
      'Word to PDF service',
      'Word to PDF website',
      'Word to PDF utility',
      'Word to PDF processor',
      'Word to PDF editor',
      'Word to PDF transformer',
      'Word to PDF extractor',
      'Word to PDF parser',
      'Word to PDF reader',
      'Word to PDF writer',
      'Word to PDF generator',
      'Word to PDF creator',
      'Word to PDF maker',
      'Word to PDF builder',
      'Word to PDF formatter',
      'Word to PDF optimizer',
      'Word to PDF enhancer',
      'Word to PDF improver',
      'Word to PDF modifier',
      'Word to PDF changer',
      'Word to PDF translator'
    ],
  },
  'image-converter': {
    title: 'Image Converter - Free Online Tool | DocsAuraFlow',
    description: 'Convert images between different formats online for free. Transform JPG, PNG, GIF, WebP, and more image formats. Fast, secure, and no registration required.',
    keywords: [
      'image converter',
      'image converter online',
      'convert image format',
      'image converter free',
      'image format converter',
      'image converter tool',
      'image conversion',
      'image converter software',
      'image converter app',
      'image converter service',
      'image converter website',
      'image converter utility',
      'image converter processor',
      'image converter editor',
      'image converter transformer',
      'image converter extractor',
      'image converter parser',
      'image converter reader',
      'image converter writer',
      'image converter generator',
      'image converter creator',
      'image converter maker',
      'image converter builder',
      'image converter formatter',
      'image converter optimizer',
      'image converter enhancer',
      'image converter improver',
      'image converter modifier',
      'image converter changer',
      'image converter translator',
      'JPG to PNG',
      'PNG to JPG',
      'GIF to PNG',
      'WebP to JPG',
      'image format converter',
      'image type converter',
      'image file converter',
      'image extension converter',
      'image format changer',
      'image type changer',
      'image file changer',
      'image extension changer'
    ],
  },
  'ai-upscaler': {
    title: 'AI Image Upscaler - Free Online Tool | DocsAuraFlow',
    description: 'Enhance image quality with AI upscaling online for free. Increase image resolution and improve quality using advanced AI technology. Fast, secure, and no registration required.',
    keywords: [
      'AI image upscaler',
      'AI upscaler',
      'image upscaler',
      'AI image enhancer',
      'image enhancer',
      'AI upscaling',
      'image upscaling',
      'AI image improvement',
      'image improvement',
      'AI image enhancement',
      'image enhancement',
      'AI image quality',
      'image quality',
      'AI image resolution',
      'image resolution',
      'AI image scaling',
      'image scaling',
      'AI image processing',
      'image processing',
      'AI image optimization',
      'image optimization',
      'AI image refinement',
      'image refinement',
      'AI image sharpening',
      'image sharpening',
      'AI image clarity',
      'image clarity',
      'AI image detail',
      'image detail',
      'AI image texture',
      'image texture',
      'AI image enhancement tool',
      'image enhancement tool',
      'AI image upscaler tool',
      'image upscaler tool',
      'AI image enhancer tool',
      'image enhancer tool',
      'AI image improvement tool',
      'image improvement tool',
      'AI image optimization tool',
      'image optimization tool',
      'AI image processing tool',
      'image processing tool',
      'AI image scaling tool',
      'image scaling tool',
      'AI image resolution tool',
      'image resolution tool',
      'AI image quality tool',
      'image quality tool',
      'AI image clarity tool',
      'image clarity tool',
      'AI image detail tool',
      'image detail tool',
      'AI image texture tool',
      'image texture tool',
      'AI image sharpening tool',
      'image sharpening tool',
      'AI image refinement tool',
      'image refinement tool'
    ],
  },
  'remove-background': {
    title: 'Background Remover - Free Online Tool | DocsAuraFlow',
    description: 'Remove image backgrounds online for free. Extract subjects from images with precision using AI technology. Fast, secure, and no registration required.',
    keywords: [
      'background remover',
      'remove background',
      'background removal',
      'remove image background',
      'image background remover',
      'background removal tool',
      'remove background online',
      'background remover online',
      'remove background free',
      'background remover free',
      'remove background tool',
      'background remover tool',
      'remove background software',
      'background remover software',
      'remove background app',
      'background remover app',
      'remove background service',
      'background remover service',
      'remove background website',
      'background remover website',
      'remove background utility',
      'background remover utility',
      'remove background processor',
      'background remover processor',
      'remove background editor',
      'background remover editor',
      'remove background transformer',
      'background remover transformer',
      'remove background extractor',
      'background remover extractor',
      'remove background parser',
      'background remover parser',
      'remove background reader',
      'background remover reader',
      'remove background writer',
      'background remover writer',
      'remove background generator',
      'background remover generator',
      'remove background creator',
      'background remover creator',
      'remove background maker',
      'background remover maker',
      'remove background builder',
      'background remover builder',
      'remove background formatter',
      'background remover formatter',
      'remove background optimizer',
      'background remover optimizer',
      'remove background enhancer',
      'background remover enhancer',
      'remove background improver',
      'background remover improver',
      'remove background modifier',
      'background remover modifier',
      'remove background changer',
      'background remover changer',
      'remove background translator',
      'background remover translator',
      'AI background removal',
      'AI background remover',
      'AI remove background',
      'AI background removal tool',
      'AI background remover tool',
      'AI remove background tool',
      'AI background removal software',
      'AI background remover software',
      'AI remove background software',
      'AI background removal app',
      'AI background remover app',
      'AI remove background app',
      'AI background removal service',
      'AI background remover service',
      'AI remove background service',
      'AI background removal website',
      'AI background remover website',
      'AI remove background website',
      'AI background removal utility',
      'AI background remover utility',
      'AI remove background utility',
      'AI background removal processor',
      'AI background remover processor',
      'AI remove background processor',
      'AI background removal editor',
      'AI background remover editor',
      'AI remove background editor',
      'AI background removal transformer',
      'AI background remover transformer',
      'AI remove background transformer',
      'AI background removal extractor',
      'AI background remover extractor',
      'AI remove background extractor',
      'AI background removal parser',
      'AI background remover parser',
      'AI remove background parser',
      'AI background removal reader',
      'AI background remover reader',
      'AI remove background reader',
      'AI background removal writer',
      'AI background remover writer',
      'AI remove background writer',
      'AI background removal generator',
      'AI background remover generator',
      'AI remove background generator',
      'AI background removal creator',
      'AI background remover creator',
      'AI remove background creator',
      'AI background removal maker',
      'AI background remover maker',
      'AI remove background maker',
      'AI background removal builder',
      'AI background remover builder',
      'AI remove background builder',
      'AI background removal formatter',
      'AI background remover formatter',
      'AI remove background formatter',
      'AI background removal optimizer',
      'AI background remover optimizer',
      'AI remove background optimizer',
      'AI background removal enhancer',
      'AI background remover enhancer',
      'AI remove background enhancer',
      'AI background removal improver',
      'AI background remover improver',
      'AI remove background improver',
      'AI background removal modifier',
      'AI background remover modifier',
      'AI remove background modifier',
      'AI background removal changer',
      'AI background remover changer',
      'AI remove background changer',
      'AI background removal translator',
      'AI background remover translator',
      'AI remove background translator'
    ],
  },
  'resume-builder': {
    title: 'Resume Builder - Free Online Tool | DocsAuraFlow',
    description: 'Create professional resumes online for free. Choose from modern templates and build your resume with ease. Fast, secure, and no registration required.',
    keywords: [
      'resume builder',
      'resume creator',
      'resume maker',
      'resume generator',
      'resume template',
      'resume builder online',
      'resume creator online',
      'resume maker online',
      'resume generator online',
      'resume template online',
      'resume builder free',
      'resume creator free',
      'resume maker free',
      'resume generator free',
      'resume template free',
      'resume builder tool',
      'resume creator tool',
      'resume maker tool',
      'resume generator tool',
      'resume template tool',
      'resume builder software',
      'resume creator software',
      'resume maker software',
      'resume generator software',
      'resume template software',
      'resume builder app',
      'resume creator app',
      'resume maker app',
      'resume generator app',
      'resume template app',
      'resume builder service',
      'resume creator service',
      'resume maker service',
      'resume generator service',
      'resume template service',
      'resume builder website',
      'resume creator website',
      'resume maker website',
      'resume generator website',
      'resume template website',
      'resume builder utility',
      'resume creator utility',
      'resume maker utility',
      'resume generator utility',
      'resume template utility',
      'resume builder processor',
      'resume creator processor',
      'resume maker processor',
      'resume generator processor',
      'resume template processor',
      'resume builder editor',
      'resume creator editor',
      'resume maker editor',
      'resume generator editor',
      'resume template editor',
      'resume builder transformer',
      'resume creator transformer',
      'resume maker transformer',
      'resume generator transformer',
      'resume template transformer',
      'resume builder extractor',
      'resume creator extractor',
      'resume maker extractor',
      'resume generator extractor',
      'resume template extractor',
      'resume builder parser',
      'resume creator parser',
      'resume maker parser',
      'resume generator parser',
      'resume template parser',
      'resume builder reader',
      'resume creator reader',
      'resume maker reader',
      'resume generator reader',
      'resume template reader',
      'resume builder writer',
      'resume creator writer',
      'resume maker writer',
      'resume generator writer',
      'resume template writer',
      'resume builder formatter',
      'resume creator formatter',
      'resume maker formatter',
      'resume generator formatter',
      'resume template formatter',
      'resume builder optimizer',
      'resume creator optimizer',
      'resume maker optimizer',
      'resume generator optimizer',
      'resume template optimizer',
      'resume builder enhancer',
      'resume creator enhancer',
      'resume maker enhancer',
      'resume generator enhancer',
      'resume template enhancer',
      'resume builder improver',
      'resume creator improver',
      'resume maker improver',
      'resume generator improver',
      'resume template improver',
      'resume builder modifier',
      'resume creator modifier',
      'resume maker modifier',
      'resume generator modifier',
      'resume template modifier',
      'resume builder changer',
      'resume creator changer',
      'resume maker changer',
      'resume generator changer',
      'resume template changer',
      'resume builder translator',
      'resume creator translator',
      'resume maker translator',
      'resume generator translator',
      'resume template translator',
      'professional resume',
      'professional resume builder',
      'professional resume creator',
      'professional resume maker',
      'professional resume generator',
      'professional resume template',
      'modern resume',
      'modern resume builder',
      'modern resume creator',
      'modern resume maker',
      'modern resume generator',
      'modern resume template',
      'CV builder',
      'CV creator',
      'CV maker',
      'CV generator',
      'CV template',
      'CV builder online',
      'CV creator online',
      'CV maker online',
      'CV generator online',
      'CV template online',
      'CV builder free',
      'CV creator free',
      'CV maker free',
      'CV generator free',
      'CV template free',
      'CV builder tool',
      'CV creator tool',
      'CV maker tool',
      'CV generator tool',
      'CV template tool',
      'CV builder software',
      'CV creator software',
      'CV maker software',
      'CV generator software',
      'CV template software',
      'CV builder app',
      'CV creator app',
      'CV maker app',
      'CV generator app',
      'CV template app',
      'CV builder service',
      'CV creator service',
      'CV maker service',
      'CV generator service',
      'CV template service',
      'CV builder website',
      'CV creator website',
      'CV maker website',
      'CV generator website',
      'CV template website',
      'CV builder utility',
      'CV creator utility',
      'CV maker utility',
      'CV generator utility',
      'CV template utility',
      'CV builder processor',
      'CV creator processor',
      'CV maker processor',
      'CV generator processor',
      'CV template processor',
      'CV builder editor',
      'CV creator editor',
      'CV maker editor',
      'CV generator editor',
      'CV template editor',
      'CV builder transformer',
      'CV creator transformer',
      'CV maker transformer',
      'CV generator transformer',
      'CV template transformer',
      'CV builder extractor',
      'CV creator extractor',
      'CV maker extractor',
      'CV generator extractor',
      'CV template extractor',
      'CV builder parser',
      'CV creator parser',
      'CV maker parser',
      'CV generator parser',
      'CV template parser',
      'CV builder reader',
      'CV creator reader',
      'CV maker reader',
      'CV generator reader',
      'CV template reader',
      'CV builder writer',
      'CV creator writer',
      'CV maker writer',
      'CV generator writer',
      'CV template writer',
      'CV builder formatter',
      'CV creator formatter',
      'CV maker formatter',
      'CV generator formatter',
      'CV template formatter',
      'CV builder optimizer',
      'CV creator optimizer',
      'CV maker optimizer',
      'CV generator optimizer',
      'CV template optimizer',
      'CV builder enhancer',
      'CV creator enhancer',
      'CV maker enhancer',
      'CV generator enhancer',
      'CV template enhancer',
      'CV builder improver',
      'CV creator improver',
      'CV maker improver',
      'CV generator improver',
      'CV template improver',
      'CV builder modifier',
      'CV creator modifier',
      'CV maker modifier',
      'CV generator modifier',
      'CV template modifier',
      'CV builder changer',
      'CV creator changer',
      'CV maker changer',
      'CV generator changer',
      'CV template changer',
      'CV builder translator',
      'CV creator translator',
      'CV maker translator',
      'CV generator translator',
      'CV template translator',
      'professional CV',
      'professional CV builder',
      'professional CV creator',
      'professional CV maker',
      'professional CV generator',
      'professional CV template',
      'modern CV',
      'modern CV builder',
      'modern CV creator',
      'modern CV maker',
      'modern CV generator',
      'modern CV template'
    ],
  },
  'pdf-form-filler': {
    title: 'PDF Form Filler - Free Online Tool | DocsAuraFlow',
    description: 'Fill PDF forms online for free. Edit and fill PDF forms with ease. Fast, secure, and no registration required.',
    keywords: [
      'PDF form filler',
      'fill PDF form',
      'PDF form editor',
      'edit PDF form',
      'PDF form filler online',
      'fill PDF form online',
      'PDF form editor online',
      'edit PDF form online',
      'PDF form filler free',
      'fill PDF form free',
      'PDF form editor free',
      'edit PDF form free',
      'PDF form filler tool',
      'fill PDF form tool',
      'PDF form editor tool',
      'edit PDF form tool',
      'PDF form filler software',
      'fill PDF form software',
      'PDF form editor software',
      'edit PDF form software',
      'PDF form filler app',
      'fill PDF form app',
      'PDF form editor app',
      'edit PDF form app',
      'PDF form filler service',
      'fill PDF form service',
      'PDF form editor service',
      'edit PDF form service',
      'PDF form filler website',
      'fill PDF form website',
      'PDF form editor website',
      'edit PDF form website',
      'PDF form filler utility',
      'fill PDF form utility',
      'PDF form editor utility',
      'edit PDF form utility',
      'PDF form filler processor',
      'fill PDF form processor',
      'PDF form editor processor',
      'edit PDF form processor',
      'PDF form filler transformer',
      'fill PDF form transformer',
      'PDF form editor transformer',
      'edit PDF form transformer',
      'PDF form filler extractor',
      'fill PDF form extractor',
      'PDF form editor extractor',
      'edit PDF form extractor',
      'PDF form filler parser',
      'fill PDF form parser',
      'PDF form editor parser',
      'edit PDF form parser',
      'PDF form filler reader',
      'fill PDF form reader',
      'PDF form editor reader',
      'edit PDF form reader',
      'PDF form filler writer',
      'fill PDF form writer',
      'PDF form editor writer',
      'edit PDF form writer',
      'PDF form filler generator',
      'fill PDF form generator',
      'PDF form editor generator',
      'edit PDF form generator',
      'PDF form filler creator',
      'fill PDF form creator',
      'PDF form editor creator',
      'edit PDF form creator',
      'PDF form filler maker',
      'fill PDF form maker',
      'PDF form editor maker',
      'edit PDF form maker',
      'PDF form filler builder',
      'fill PDF form builder',
      'PDF form editor builder',
      'edit PDF form builder',
      'PDF form filler formatter',
      'fill PDF form formatter',
      'PDF form editor formatter',
      'edit PDF form formatter',
      'PDF form filler optimizer',
      'fill PDF form optimizer',
      'PDF form editor optimizer',
      'edit PDF form optimizer',
      'PDF form filler enhancer',
      'fill PDF form enhancer',
      'PDF form editor enhancer',
      'edit PDF form enhancer',
      'PDF form filler improver',
      'fill PDF form improver',
      'PDF form editor improver',
      'edit PDF form improver',
      'PDF form filler modifier',
      'fill PDF form modifier',
      'PDF form editor modifier',
      'edit PDF form modifier',
      'PDF form filler changer',
      'fill PDF form changer',
      'PDF form editor changer',
      'edit PDF form changer',
      'PDF form filler translator',
      'fill PDF form translator',
      'PDF form editor translator',
      'edit PDF form translator',
      'PDF form completion',
      'complete PDF form',
      'PDF form completion online',
      'complete PDF form online',
      'PDF form completion free',
      'complete PDF form free',
      'PDF form completion tool',
      'complete PDF form tool',
      'PDF form completion software',
      'complete PDF form software',
      'PDF form completion app',
      'complete PDF form app',
      'PDF form completion service',
      'complete PDF form service',
      'PDF form completion website',
      'complete PDF form website',
      'PDF form completion utility',
      'complete PDF form utility',
      'PDF form completion processor',
      'complete PDF form processor',
      'PDF form completion editor',
      'complete PDF form editor',
      'PDF form completion transformer',
      'complete PDF form transformer',
      'PDF form completion extractor',
      'complete PDF form extractor',
      'PDF form completion parser',
      'complete PDF form parser',
      'PDF form completion reader',
      'complete PDF form reader',
      'PDF form completion writer',
      'complete PDF form writer',
      'PDF form completion generator',
      'complete PDF form generator',
      'PDF form completion creator',
      'complete PDF form creator',
      'PDF form completion maker',
      'complete PDF form maker',
      'PDF form completion builder',
      'complete PDF form builder',
      'PDF form completion formatter',
      'complete PDF form formatter',
      'PDF form completion optimizer',
      'complete PDF form optimizer',
      'PDF form completion enhancer',
      'complete PDF form enhancer',
      'PDF form completion improver',
      'complete PDF form improver',
      'PDF form completion modifier',
      'complete PDF form modifier',
      'PDF form completion changer',
      'complete PDF form changer',
      'PDF form completion translator',
      'complete PDF form translator'
    ],
  },
  'image-editor': {
    title: 'Image Editor - Free Online Tool | DocsAuraFlow',
    description: 'Edit images online for free. Crop, resize, add filters, and customize your images with our powerful online editor. Fast, secure, and no registration required.',
    keywords: [
      'image editor',
      'online image editor',
      'free image editor',
      'image editing tool',
      'image editor online',
      'image editor free',
      'image editor tool',
      'image editor software',
      'image editor app',
      'image editor service',
      'image editor website',
      'image editor utility',
      'image editor processor',
      'image editor transformer',
      'image editor extractor',
      'image editor parser',
      'image editor reader',
      'image editor writer',
      'image editor generator',
      'image editor creator',
      'image editor maker',
      'image editor builder',
      'image editor formatter',
      'image editor optimizer',
      'image editor enhancer',
      'image editor improver',
      'image editor modifier',
      'image editor changer',
      'image editor translator',
      'photo editor',
      'online photo editor',
      'free photo editor',
      'photo editing tool',
      'photo editor online',
      'photo editor free',
      'photo editor tool',
      'photo editor software',
      'photo editor app',
      'photo editor service',
      'photo editor website',
      'photo editor utility',
      'photo editor processor',
      'photo editor transformer',
      'photo editor extractor',
      'photo editor parser',
      'photo editor reader',
      'photo editor writer',
      'photo editor generator',
      'photo editor creator',
      'photo editor maker',
      'photo editor builder',
      'photo editor formatter',
      'photo editor optimizer',
      'photo editor enhancer',
      'photo editor improver',
      'photo editor modifier',
      'photo editor changer',
      'photo editor translator',
      'image crop',
      'crop image',
      'image crop tool',
      'crop image tool',
      'image crop online',
      'crop image online',
      'image crop free',
      'crop image free',
      'image resize',
      'resize image',
      'image resize tool',
      'resize image tool',
      'image resize online',
      'resize image online',
      'image resize free',
      'resize image free',
      'image filter',
      'image filters',
      'image filter tool',
      'image filters tool',
      'image filter online',
      'image filters online',
      'image filter free',
      'image filters free',
      'image effects',
      'image effect',
      'image effects tool',
      'image effect tool',
      'image effects online',
      'image effect online',
      'image effects free',
      'image effect free',
      'image adjustment',
      'image adjustments',
      'image adjustment tool',
      'image adjustments tool',
      'image adjustment online',
      'image adjustments online',
      'image adjustment free',
      'image adjustments free',
      'image enhancement',
      'image enhance',
      'image enhancement tool',
      'image enhance tool',
      'image enhancement online',
      'image enhance online',
      'image enhancement free',
      'image enhance free',
      'image optimization',
      'image optimize',
      'image optimization tool',
      'image optimize tool',
      'image optimization online',
      'image optimize online',
      'image optimization free',
      'image optimize free',
      'image modification',
      'image modify',
      'image modification tool',
      'image modify tool',
      'image modification online',
      'image modify online',
      'image modification free',
      'image modify free',
      'image transformation',
      'image transform',
      'image transformation tool',
      'image transform tool',
      'image transformation online',
      'image transform online',
      'image transformation free',
      'image transform free',
      'image manipulation',
      'image manipulate',
      'image manipulation tool',
      'image manipulate tool',
      'image manipulation online',
      'image manipulate online',
      'image manipulation free',
      'image manipulate free',
      'image processing',
      'image process',
      'image processing tool',
      'image process tool',
      'image processing online',
      'image process online',
      'image processing free',
      'image process free',
      'image editing',
      'image edit',
      'image editing tool',
      'image edit tool',
      'image editing online',
      'image edit online',
      'image editing free',
      'image edit free',
      'photo editing',
      'photo edit',
      'photo editing tool',
      'photo edit tool',
      'photo editing online',
      'photo edit online',
      'photo editing free',
      'photo edit free',
      'photo crop',
      'crop photo',
      'photo crop tool',
      'crop photo tool',
      'photo crop online',
      'crop photo online',
      'photo crop free',
      'crop photo free',
      'photo resize',
      'resize photo',
      'photo resize tool',
      'resize photo tool',
      'photo resize online',
      'resize photo online',
      'photo resize free',
      'resize photo free',
      'photo filter',
      'photo filters',
      'photo filter tool',
      'photo filters tool',
      'photo filter online',
      'photo filters online',
      'photo filter free',
      'photo filters free',
      'photo effects',
      'photo effect',
      'photo effects tool',
      'photo effect tool',
      'photo effects online',
      'photo effect online',
      'photo effects free',
      'photo effect free',
      'photo adjustment',
      'photo adjustments',
      'photo adjustment tool',
      'photo adjustments tool',
      'photo adjustment online',
      'photo adjustments online',
      'photo adjustment free',
      'photo adjustments free',
      'photo enhancement',
      'photo enhance',
      'photo enhancement tool',
      'photo enhance tool',
      'photo enhancement online',
      'photo enhance online',
      'photo enhancement free',
      'photo enhance free',
      'photo optimization',
      'photo optimize',
      'photo optimization tool',
      'photo optimize tool',
      'photo optimization online',
      'photo optimize online',
      'photo optimization free',
      'photo optimize free',
      'photo modification',
      'photo modify',
      'photo modification tool',
      'photo modify tool',
      'photo modification online',
      'photo modify online',
      'photo modification free',
      'photo modify free',
      'photo transformation',
      'photo transform',
      'photo transformation tool',
      'photo transform tool',
      'photo transformation online',
      'photo transform online',
      'photo transformation free',
      'photo transform free',
      'photo manipulation',
      'photo manipulate',
      'photo manipulation tool',
      'photo manipulate tool',
      'photo manipulation online',
      'photo manipulate online',
      'photo manipulation free',
      'photo manipulate free',
      'photo processing',
      'photo process',
      'photo processing tool',
      'photo process tool',
      'photo processing online',
      'photo process online',
      'photo processing free',
      'photo process free'
    ],
  },
};

export function generateMetadata(page: string): Metadata {
  const pageConfig = toolPages[page as keyof typeof toolPages];
  
  if (!pageConfig) {
    return {
      title: seoConfig.siteName,
      description: seoConfig.description,
      keywords: seoConfig.keywords,
    };
  }

  return {
    title: pageConfig.title,
    description: pageConfig.description,
    keywords: [...seoConfig.keywords, ...pageConfig.keywords],
    openGraph: {
      title: pageConfig.title,
      description: pageConfig.description,
      url: `${seoConfig.baseUrl}/${page}`,
      siteName: seoConfig.siteName,
      type: 'website',
      locale: 'en_US',
    },
    twitter: {
      card: 'summary_large_image',
      title: pageConfig.title,
      description: pageConfig.description,
    },
    alternates: {
      canonical: `${seoConfig.baseUrl}/${page}`,
    },
  };
} 